Repository Wurst-Imperium/Wurst7, pull requests merged in 2022-10, with the labels that each got.

#710 Update uk_ua.json
  src/main/resources/assets/wurst/lang/uk_ua.json
Labels: translation

#718 Add waitTime setting to AutoReconnectHack (issue #716)
  src/main/java/net/wurstclient/hacks/AutoReconnectHack.java
  src/main/java/net/wurstclient/mixin/DisconnectedScreenMixin.java
Labels: enhancement, settings, cat:other

#719 Add delay setting to AutoTotemHack (issue #656)
  src/main/java/net/wurstclient/hacks/AutoTotemHack.java
Labels: enhancement, settings, cat:combat
