Repository Wurst-Imperium/Wurst7, pull requests merged in 2022-02, with the labels that each got.

#549 Update zh_tw language files to the latest version
  src/main/resources/assets/wurst/lang/zh_tw.json
Labels: confirmed, translation

#562 Update "zh_cn","zh_tw" translation to the latest version
  src/main/resources/assets/wurst/lang/zh_cn.json
  src/main/resources/assets/wurst/lang/zh_tw.json
Labels: translation

#563 Add "nocomcrash" to pl_pl translation
  src/main/resources/assets/wurst/lang/pl_pl.json
Labels: translation

#566 Fix Flight Typo
  src/main/resources/assets/wurst/lang/en_us.json
Labels: bugfix, confirmed

#580 Russian translation
  src/main/resources/assets/wurst/lang/ru_ru.json
Labels: reviews wanted, translation

#555 zh_hk.json Translation
  src/main/resources/assets/wurst/lang/zh_hk.json
Labels: translation
