Repository Wurst-Imperium/Wurst7, pull requests merged in 2022-06, with the labels that each got.

#552 French Translation
  src/main/resources/assets/wurst/lang/fr_fr
Labels: reviews wanted, translation

#659 Update zh_cn.json
  src/main/resources/assets/wurst/lang/zh_cn.json
Labels: translation

#662 Wurst czech translation v1.0
  src/main/resources/assets/wurst/lang/cs_cz.json
Labels: translation

#653 Update ja_jp.json
  src/main/resources/assets/wurst/lang/ja_jp.json
Labels: translation

#619 Update zh_hk.json to newest version.
  src/main/resources/assets/wurst/lang/zh_hk.json
Labels: translation

#647 Update zh_tw.json
  src/main/resources/assets/wurst/lang/zh_tw.json
Labels: translation

#650 Update uk_ua.json
  src/main/resources/assets/wurst/lang/uk_ua.json
Labels: translation

#667 fix broken AntiBlindHack on 1.19
  .github/workflows/jsonsyntax.yml
  src/main/java/net/wurstclient/mixin/FluidBlockMixin.java
  src/main/java/net/wurstclient/mixin/GameMenuScreenMixin.java
  src/main/java/net/wurstclient/mixin/GameRendererMixin.java
  src/main/resources/assets/wurst/lang/uk_ua.json
  src/main/resources/assets/wurst/lang/zh_tw.json
Labels: bugfix, cat:render
