Repository Wurst-Imperium/Wurst7, pull requests merged in 2023-03, with the labels that each got.

#796 More FeedAura options
  src/main/java/net/wurstclient/hacks/FeedAuraHack.java
Labels: type:enhancement, area:settings, category:other

#806 SneakHack fly detection
  src/main/java/net/wurstclient/hacks/SneakHack.java
Labels: type:enhancement, area:settings, category:movement

#775 Fix AutoFarm crashing on second activation
  src/main/java/net/wurstclient/hacks/AutoFarmHack.java
Labels: issue:could not reproduce, type:bugfix, category:blocks
