Repository Wurst-Imperium/Wurst7, pull requests merged in 2023-10, with the labels that each got.

#799 Fix dolphin and fish hack
  src/main/java/net/wurstclient/hacks/DolphinHack.java
  src/main/java/net/wurstclient/hacks/FishHack.java
Labels: status:merged, type:bugfix, category:movement, status:confirmed

#825 AntiBlind fix
  src/main/java/net/wurstclient/hacks/AntiBlindHack.java
  src/main/java/net/wurstclient/mixin/ClientPlayerEntityMixin.java
  src/main/java/net/wurstclient/mixin/LightTextureManagerMixin.java
  src/main/resources/wurst.mixins.json
Labels: status:merged, type:bugfix, category:render

#830 Fix tracers shaking in vehicles
  src/main/java/net/wurstclient/hacks/ChestEspHack.java
  src/main/java/net/wurstclient/hacks/FreecamHack.java
  src/main/java/net/wurstclient/hacks/ItemEspHack.java
  src/main/java/net/wurstclient/hacks/MobEspHack.java
  src/main/java/net/wurstclient/hacks/PlayerEspHack.java
  src/main/java/net/wurstclient/hacks/chestesp/ChestEspRenderer.java
  src/main/java/net/wurstclient/util/RotationUtils.java
Labels: status:merged, type:bugfix, status:confirmed

#886 Check Line of sight in Aim Assist
  src/main/java/net/wurstclient/hacks/AimAssistHack.java
Labels: type:enhancement, status:merged, area:settings, category:combat

#890 Added if entity is friend sword won't be pulled
  src/main/java/net/wurstclient/hacks/AutoSwordHack.java
Labels: type:bugfix, category:combat
