Repository Wurst-Imperium/Wurst7, pull requests merged in 2023-11, with the labels that each got.

#743 BarrierEsp
  src/main/java/net/wurstclient/hack/HackList.java
  src/main/java/net/wurstclient/hacks/BarrierEspHack.java
  src/main/java/net/wurstclient/mixin/ClientWorldMixin.java
  src/main/resources/assets/wurst/lang/en_us.json
  src/main/resources/wurst.mixins.json
Labels: type:enhancement, status:merged, type:new feature, category:render

#792 Added AutoRespawn to DeathScreen
  src/main/java/net/wurstclient/hacks/AutoRespawnHack.java
  src/main/java/net/wurstclient/mixin/DeathScreenMixin.java
Labels: type:enhancement, status:merged, area:gui, category:combat

#893 Update Korean Description
  src/main/resources/assets/wurst/lang/ko_kr.json
Labels: status:merged, type:translation

#899 Add MassTpahere tab
  src/main/java/net/wurstclient/hacks/MassTpaHack.java
Labels: type:enhancement, status:merged, area:settings, category:chat, area:command
