Repository Wurst-Imperium/Wurst7, pull requests merged in 2024-06, with the labels that each got.

#826 AutoLeave totem check
  src/main/java/net/wurstclient/hacks/AutoLeaveHack.java
Labels: type:enhancement, status:merged, area:settings, category:combat, area:inventory, status:never-stale

#999 Update zh_cn.json
  src/main/resources/assets/wurst/lang/zh_cn.json
Labels: status:merged, type:translation

#1013 Japanese translations for v7.44
  src/main/resources/assets/wurst/lang/ja_jp.json
Labels: type:translation, status:never-stale
