Repository Wurst-Imperium/Wurst7, pull requests merged in 2024-07, with the labels that each got.

#1008 Update zh_cn.json
  src/main/resources/assets/wurst/lang/zh_cn.json
Labels: status:merged, type:translation, status:never-stale

#1016 Added option for guide boxes to show where airplace will place blocks
  src/main/java/net/wurstclient/hacks/AirPlaceHack.java
  src/main/resources/assets/wurst/lang/en_us.json
Labels: type:enhancement, status:merged, area:settings, category:blocks, status:never-stale

#1031 Fix PacketOutputEvent
  src/main/java/net/wurstclient/mixin/ClientCommonNetworkHandlerMixin.java
Labels: status:merged, type:bugfix, category:movement, status:never-stale

#1035 Convert Redirect to WrapOperation
  src/main/java/net/wurstclient/mixin/LivingEntityRendererMixin.java
Labels: status:merged, type:bugfix, area:compatibility, status:never-stale
