Repository Wurst-Imperium/Wurst7, pull requests merged in 2024-05, with the labels that each got.

#962 Ignore unbreakable blocks in FastBreak
  src/main/java/net/wurstclient/hacks/FastBreakHack.java
Labels: status:merged, type:bugfix, category:blocks, status:never-stale

#982 Add Slider to AntiAFK for Custom Movement Increment Setting
  src/main/java/net/wurstclient/hacks/AntiAfkHack.java
Labels: type:enhancement, status:merged, area:settings, category:other

#996 replace rangeSq to range.getValueSq()
  src/main/java/net/wurstclient/hacks/KillauraHack.java
Labels: type:refactor
