Repository Wurst-Imperium/Wurst7, pull requests merged in 2025-06, with the labels that each got.

#1156 Redid 1.21.6 NoFog to be like previous versions
  src/main/java/net/wurstclient/mixin/AtmosphericFogModifierMixin.java
  src/main/java/net/wurstclient/mixin/DimensionOrBossFogModifierMixin.java
  src/main/java/net/wurstclient/mixin/FogRendererMixin.java
  src/main/resources/wurst.mixins.json
Labels: type:enhancement, category:render, status:never-stale

#919 Add option to temporarily disable Glide hack while sneaking
  src/main/java/net/wurstclient/hacks/GlideHack.java
Labels: type:enhancement, status:merged, area:settings, category:movement

#1151 Fixed NoFog
  src/main/java/net/wurstclient/mixin/BackgroundRendererMixin.java
Labels: status:merged, type:bugfix, category:render

#1153 NoOverlay - Completed Powdered Snow Implementation
  src/main/java/net/wurstclient/hacks/NoOverlayHack.java
  src/main/java/net/wurstclient/mixin/IngameHudMixin.java
  src/main/resources/assets/wurst/translations/cs_cz.json
  src/main/resources/assets/wurst/translations/en_us.json
  src/main/resources/assets/wurst/translations/fr_fr.json
  src/main/resources/assets/wurst/translations/it_it.json
  src/main/resources/assets/wurst/translations/ja_jp.json
  src/main/resources/assets/wurst/translations/ko_kr.json
  src/main/resources/assets/wurst/translations/pl_pl.json
  src/main/resources/assets/wurst/translations/ro_ro.json
  src/main/resources/assets/wurst/translations/ru_ru.json
  src/main/resources/assets/wurst/translations/tr_tr.json
  src/main/resources/assets/wurst/translations/uk_ua.json
  src/main/resources/assets/wurst/translations/zh_cn.json
  src/main/resources/assets/wurst/translations/zh_hk.json
  src/main/resources/assets/wurst/translations/zh_tw.json
Labels: type:enhancement, status:merged, category:render

#1155 Fix FakePlayerEntity pushing away the player
  src/main/java/net/wurstclient/util/FakePlayerEntity.java
Labels: status:merged, type:bugfix, category:movement
